const products = [
    {
        type: 'men-sneakers',
        image: '/images/product_p1.png',
        company: 'Adidas',
        product: 'Sneakers',
        rating: 4.5,
        sp: 249,
        mrp: 300,
        discount: 17,
        desc: {
            details: "A pair of round-toe white sneakers, has regular styling, lace-up detail",
            material: "Canvas material. Wipe with a clean, dry cloth to remove dust",
            specsType: "Sneakers",
            specsToe: "Round Toe",
            specsPattern: "Solid",
            specsFastening: "Lace Ups",
            specsWidth: "Regular",
            specsSole: "Rubber",
            specsWarranty: "3 months",
        }
    },
    {
        type: 'men-sneakers',
        image: '/images/product_p2.png',
        company: 'U.S. Polo Assn.',
        product: 'Men Grey Clarkin Sneakers',
        rating: 4.7,
        sp: 2099,
        mrp: 2999,
        discount: 30,
        desc: {
            details: "A pair of round-toe white sneakers, has regular styling, lace-up detail",
            material: "Canvas material. Wipe with a clean, dry cloth to remove dust",
            specsType: "Sneakers",
            specsToe: "Round Toe",
            specsPattern: "Solid",
            specsFastening: "Lace Ups",
            specsWidth: "Regular",
            specsSole: "Rubber",
            specsWarranty: "3 months",
        }
    },
    {
        type: 'men-sneakers',
        image: '/images/product_p3.jpg',
        company: 'Roadster',
        product: 'Men Black Sneakers',
        rating: 4.7,
        sp: 872,
        mrp: 3795,
        discount: 77,
        desc: {
            details: "A pair of round-toe black sneakers, has regular styling, lace-up detail",
            material: "Wipe gently with a dry cloth to remove any dried-on dirt and dust",
            specsType: "Sneakers",
            specsToe: "Round Toe",
            specsPattern: "Solid",
            specsFastening: "Lace Ups",
            specsWidth: "Regular",
            specsSole: "TPR",
            specsWarranty: "3 months",
        }
    },
    {
        type: 'men-loafers',
        image: '/images/product_p4.png',
        company: 'Provogue',
        product: 'Men Tan Brown Solid Formal Loafers',
        rating: 4.2,
        sp: 879,
        mrp: 4395,
        discount: 80,
        desc: {
            details: "A pair of tan brown round-toed formal loafers, has regular styling",
            material: "Synthetic leather. Allow your pair of shoes to air and de-odorize at regular basis. Use shoe bags to prevent any stains or mildew. Dust any dry dirt from the surface using a clean cloth. Do not use polish or shiner",
            specsType: "Loafers",
            specsToe: "Round Toe",
            specsPattern: "Solid",
            specsFastening: "Slip On",
            specsWidth: "Regular",
            specsSole: "Rubber",
            specsWarranty: "3 months",
        }
    },
    {
        type: 'men-loafers',
        image: '/images/product_p5.jpg',
        company: 'U.S. Polo Assn.',
        product: 'U S Polo Assn Men Navy Blue PU Loafers',
        rating: 3.9,
        sp: 2239,
        mrp: 3199,
        discount: 30,
        desc: {
            details: "A pair of square toe navy blue ,has regular styling, slip-on detail",
            material: "Wipe with a clean, dry cloth to remove dust",
            specsType: "Loafers",
            specsToe: "Square Toe",
            specsPattern: "Solid",
            specsFastening: "Slip On",
            specsWidth: "Regular",
            specsSole: "TPR",
            specsWarranty: "3 months",
        }
    },
    {
        type: 'men-loafers',
        image: '/images/product_p6.jpg',
        company: 'HIGHLANDER',
        product: 'Men Solid Leather Loafers',
        rating: 3.9,
        sp: 1094,
        mrp: 1990,
        discount: 45,
        desc: {
            details: "A pair of square toe leather loafers, has regular styling, slip-on detail",
            material: "Wipe with a clean, dry cloth to remove dust",
            specsType: "Loafers",
            specsToe: "Square Toe",
            specsPattern: "Solid",
            specsFastening: "Slip On",
            specsWidth: "Regular",
            specsSole: "PVC",
            specsWarranty: "4 months",
        }
    },
    {
        type: 'men-chelsea',
        image: '/images/product_p7.jpg',
        company: 'H&M',
        product: 'Men Brown Chelsea boots',
        rating: 4.1,
        sp: 1199,
        mrp: 3999,
        discount: 30,
        desc: {
            details: "Chelsea boots in soft imitation suede with elastic gores in the sides and a loop at the back. Linings and insoles in imitation leather and cotton canvas. Fluted soles. Heel 2.7 cm.",
            material: "100% Polyester",
            specsType: "Chelsea Boots",
            specsToe: "Pointed Toe",
            specsPattern: "Solid",
            specsFastening: "Slip On",
            specsWidth: "Regular",
            specsSole: "Synthetic",
            specsWarranty: "2 months",
        }
    },
    {
        type: 'men-chelsea',
        image: '/images/product_p8.jpg',
        company: 'Fentacia',
        product: 'Men Brown Solid Synthetic Leather Lightweight High-Top Flat Chelsea Boots',
        rating: 4.0,
        sp: 1259,
        mrp: 5999,
        discount: 79,
        desc: {
            details: "A pair of round-toe brown flat boots, has high-top styling, slip-on detail",
            material: "Synthetic Leather. Wipe with a clean, dry cloth to remove dust",
            specsType: "Chelsea Boots",
            specsToe: "Round Toe",
            specsPattern: "Solid",
            specsFastening: "Slip On",
            specsWidth: "Narrow",
            specsSole: "TPR",
            specsWarranty: "1 month",
        }
    },
    {
        type: 'men-chelsea',
        image: '/images/product_p9.jpg',
        company: 'Roadster',
        product: 'Men Black Matte Rugged Chelsea Boots',
        rating: 4.1,
        sp: 1169,
        mrp: 2599,
        discount: 55,
        desc: {
            details: "A pair of round toe black matte rugged chelsea boots , has regular styling, slip-on detail",
            material: "Upper material: Synthetic Suede. Use a branded leather conditioner to clean the product/wipe with a clean, dry cloth to remove the dust",
            specsType: "Chelsea Boots",
            specsToe: "Round Toe",
            specsPattern: "Solid",
            specsFastening: "Slip On",
            specsWidth: "Regular",
            specsSole: "TPR",
            specsWarranty: "1 month",
        }
    },
    {
        type: 'men-walking',
        image: '/images/product_p10.jpeg',
        company: 'Reebok',
        product: 'Men Navy Blue Mesh Walking Non-Marking Shoes',
        rating: 4.4,
        sp: 1439,
        mrp: 4799,
        discount: 70,
        desc: {
            details: "A pair of navy blue shoes, has regular styling, slip-on detail",
            material: "Care Instruction: Wipe with a clean, dry cloth to remove the dust.",
            specsType: "Walking Shoes",
            specsToe: "Round Toe",
            specsPattern: "Mesh",
            specsFastening: "Slip On",
            specsWidth: "Regular",
            specsSole: "Rubber",
            specsWarranty: "45 days",
        }
    },
    {
        type: 'men-walking',
        image: '/images/product_p11.jpg',
        company: 'Campus',
        product: 'Men Blue Mesh Walking Non-Marking Shoes',
        rating: 4.4,
        sp: 899,
        mrp: 999,
        discount: 10,
        desc: {
            details: "A pair of navy blue shoes, has regular styling, slip-on detail",
            material: "Care Instruction: Wipe with a clean, dry cloth to remove the dust.",
            specsType: "Walking Shoes",
            specsToe: "Round Toe",
            specsPattern: "Mesh",
            specsFastening: "Slip On",
            specsWidth: "Regular",
            specsSole: "TPR",
            specsWarranty: "1 month",
        }
    },
    {
        type: 'women-walking',
        image: '/images/product_p12.jpg',
        company: 'Nike',
        product: 'Women Black Walking Non-Marking Shoes',
        rating: 4.5,
        sp: 3599,
        mrp: 3999,
        discount: 10,
        desc: {
            details: "A pair of black walking shoes, has regular Styling, lace-ups detail",
            material: "Upper material: PU. Wipe with a clean, dry cloth to remove the dust",
            specsType: "Walking Shoes",
            specsToe: "Round Toe",
            specsPattern: "Mesh",
            specsFastening: "Lace-Ups",
            specsWidth: "Regular",
            specsSole: "Rubber",
            specsWarranty: "1 month",
        }
    },
    {
        type: 'men-sandals',
        image: '/images/product_p13.jpg',
        company: 'El Paso',
        product: 'Men Black Comfort Sandals',
        rating: 4.1,
        sp: 779,
        mrp: 3895,
        discount: 80,
        desc: {
            details: "A pair of black comfort sandals, synthetic leather upper with slip-on closure",
            material: "Upper material: Synthetic Leather. Wipe with a clean, dry cloth to remove the dust",
            specsType: "Comfort Sandals",
            specsToe: "Open Toe",
            specsPattern: "Solid",
            specsFastening: "Slip-On",
            specsWidth: "Regular",
            specsSole: "Rubber",
            specsWarranty: "3 months",
        }
    },
    {
        type: 'men-sandals',
        image: '/images/product_p14.jpg',
        company: 'Redtape',
        product: 'Men Black Leather Comfort Sandals',
        rating: 4.6,
        sp: 1299,
        mrp: 1999,
        discount: 35,
        desc: {
            details: "A pair of black solid perforated comfort sandals, leather upper with slip-on closure",
            material: "Leather. Use a branded leather conditioner to clean the product. Avoid washing",
            specsType: "Comfort Sandals",
            specsToe: "Open Toe",
            specsPattern: "Solid",
            specsFastening: "Slip-On",
            specsWidth: "Regular",
            specsSole: "Rubber",
            specsWarranty: "6 months",
        }
    },
    {
        type: 'men-sandals',
        image: '/images/product_p15.jpg',
        company: 'Afrojack',
        product: 'Men Black Croslite Sliders',
        rating: 4,
        sp: 499,
        mrp: 2495,
        discount: 80,
        desc: {
            details: "A pair of black solid sliders",
            material: "Upper material: Croslite. Wipe with a clean, dry cloth to remove the dust",
            specsType: "Comfort Sandals",
            specsToe: "Open Toe",
            specsPattern: "Solid",
            specsFastening: "Slip-On",
            specsWidth: "Regular",
            specsSole: "Croslite",
            specsWarranty: "3 months",
        }
    }
];

export default products;